using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ToDoApplication.Core.Entities;

namespace ToDoApplication.Infrastructure.Persistence;

public class CardConfiguration : IEntityTypeConfiguration<Card>
{
    public CardConfiguration(){}
    public void Configure(EntityTypeBuilder<Card> card)
    {
        card.HasKey(c => c .id);
        card.Property(c => c.title).IsRequired(true);
        card.Property(c => c.color).HasDefaultValue("#ffffff");
       
        //TODO: Add DB autogenerated value for order (Max + 1).
    }
     
}